services:
  db:
    image: postgres:14
    command: >
      -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: myfiubagymbro
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_URL: 'postgresql+psycopg2://postgres:secret@db:5432/myfiubagymbro'

  frontend:
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend